context.properties = {
    # Default sample rate when nothing specific is requested
    clock.default.rate = 96000

    # Allowed native rates PipeWire can switch to automatically
    clock.allowed-rates = [ 44100 48000 88200 96000 176400 192000 ]
}
