[color]
gradient = 1
gradient_count = 8
gradient_color_1 = '#4C4444'
gradient_color_2 = '#4C5D70'
gradient_color_3 = '#7C766C'
gradient_color_4 = '#977587'
gradient_color_5 = '#7B899E'
gradient_color_6 = '#99857A'
gradient_color_7 = '#9CB0BF'
gradient_color_8 = '#DFECF6'
