# ██╗    ██╗██╗███╗   ██╗██████╗  ██████╗ ██╗    ██╗██████╗ ██╗   ██╗██╗     ███████╗
# ██║    ██║██║████╗  ██║██╔══██╗██╔═══██╗██║    ██║██╔══██╗██║   ██║██║     ██╔════╝
# ██║ █╗ ██║██║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║██████╔╝██║   ██║██║     █████╗  
# ██║███╗██║██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║██╔══██╗██║   ██║██║     ██╔══╝  
# ╚███╔███╔╝██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝██║  ██║╚██████╔╝███████╗███████╗
#  ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚══════╝
#------------------------------------------------------------------------------------

windowrule {
  name = windowrule-1
  opacity = 0.95 0.9
  match:class = ^(org.kde.dolphin)$
}

windowrule {
  name = windowrule-2
  opacity = 0.6 0.6
  match:class = ^(Rofi)$
}

windowrule {
  name = windowrule-4
  opacity = 0.95 0.9
  match:class = ^(com.discordapp.Discord)$
}

windowrule {
  name = windowrule-5
  opacity = 0.8 0.75
  match:class = ^(kitty)$
}

windowrule {
  name = windowrule-6
  opacity = 0.95 0.9
  match:class = ^(com.mitchellh.ghostty)$
}

windowrule {
  name = windowrule-7
  opacity = 0.9 0.85
  float = on
  workspace = 2 silent
  size = 1400 790
  move = (25) (45)
  match:class = ^(dash-rmpc)$
  match:workspace = 2
}

windowrule {
  name = windowrule-8
  opacity = 0.9 0.85
  float = on
  workspace = 2 silent
  size = 445 540
  move = (1450) (45)
  match:class = ^(dash-matrix)$
  match:workspace = 2
}


windowrule {
  name = windowrule-9
  opacity = 0.9 0.85
  float = on
  workspace = 2 silent
  size = 1870 205
  move = (25) (855)
  match:class = ^(dash-cava)$
  match:workspace = 2
}

windowrule {
  name = windowrule-10
  opacity = 0.9 0.85
  float = on
  workspace = 2 silent
  size = 445 235
  move = (1450) (600)
  match:class = ^(dash-clock)$
  match:workspace = 2
}
