music_directory    "/home/einel256/Music"
playlist_directory "/home/einel256/.config/mpd/playlists"
db_file            "/home/einel256/.config/mpd/database"
log_file           "/home/einel256/.config/mpd/log"
pid_file           "/home/einel256/.config/mpd/pid"
sticker_file      "~/.local/share/mpd/sticker.sql"

audio_output {
    type            "pulse"     
    name            "PulseAudio"
    format          "48000:32:6"
}

audio_output {
    type    "fifo"
    name    "Visualizer"
    path    "/tmp/mpd.fifo"
    format  "48000:32:2"
}

input {
    plugin "curl"
}

decoder {
    plugin "ffmpeg"
}

bind_to_address "0.0.0.0"
metadata_to_use "artist,album,title,track,name,genre,date,composer,performer,disc,comment"
